version: ''

services:
  db:
    image: postgres
    restart: always
    environment:
      PG_USER: postgres
      PG_PASSWORD: postgres
      PG_DB: postgres
  api:
    build: .
    ports:
     - 8080:8080
    environment:
      - PORT=8080
      - DATABASE_URL=db
    depends_on:
      - db